include ./mocha.conf
shell /run/current-system/sw/bin/zsh
font_family Iosevka Nerd Font
font_size        12	
bold_font        auto
italic_font      auto
bold_italic_font auto
mouse_hide_wait  2.0
cursor_shape     block
# url_color        #0087bd
url_style        dotted
#Close the terminal without confirmation
confirm_os_window_close 0
background_opacity 0.55
window_padding_width 14
hide_window_decorations yes
cursor_shape beam
cursor_blink_interval 0
font_size 13

# BEGIN_KITTY_THEME
# Adapta Nokto Maia
include current-theme.conf
# END_KITTY_THEME
